model_params:
  model_name: 'DCGAN'
  latent_dim: 100
  latent_batch_size: 32
  discriminate_param:
    input_shape: [128, 128, 3]
    layers:
      - name: 'Conv2D'
        filters: 16
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 32
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 64
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 128
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 256
        kernel_size: 3
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'MaxPool2D'
        pool_size: [4,4]
        strides: [4, 4]
      - name: 'Flatten'
      - name: 'Dense'
        units: 1
        activation: 'sigmoid'
        
  generate_param:
    input_shape: [100]
    layers:
      - name: 'Dense'
        units: 4096
      - name: 'BN'
      - name: 'LeakyReLu'
      - name: 'Reshape'
        target_shape: [4, 4, 256]

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 128
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 64
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 32
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 16
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2DTranspose'
        kernel_size: 3
        filters: 8
        strides: [2,2]
        padding: 'same'
      - name: 'BN'
      - name: 'LeakyReLu'

      - name: 'Conv2D'
        filters: 3
        kernel_size: 3
        strides: [1,1]
        padding: 'same'
        activation: 'sigmoid'

dataset_params:
  path: 'data/'
  input_shape: [128, 128]
  test_split: 0.2
  batch_size: 32
  shuffle: True
  scale: 'sigmoid'

train_params:
  epochs: 50
  iter_disc: 5
  iter_gen: 1
  save_path: 'assets/'
  save_model_path: 'save/'

opt_params:
  gen_opt: 
    name : 'Adam'
    learning_rate: 0.0001
  disc_opt: 
    name : 'Adam'
    learning_rate: 0.0001